fn main() {
    // app commands get autogenerated `allow-$cmd`/`deny-$cmd` permissions
    // — the capability grants the loopback page only the window-chrome
    // verbs, nothing else of the IPC surface
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "shell_win",
            "shell_drag",
            "shell_open",
            "shell_notify",
            "shell_zoom",
            "session_events",
            "host_call",
        ]),
    ))
    .expect("tauri-build")
}
